In [1]:
import pandas as pd
from AllSpark.core.pd_compare import Compare

In [2]:
df1 = pd.read_csv(r'D:\Project\AllSpark\tests\testdata\L3_stockquotes_20160105_BAS.csv', parse_dates=['quotedate'])
df2 = pd.read_csv(r'D:\Project\AllSpark\tests\testdata\L3_stockquotes_20160105_REG.csv', parse_dates=['quotedate'])
compare = Compare(left=df1, right=df2, key_columns=['symbol'])

2019-10-30 14:54:17,749 - INFO - _merge_dataframe: Merging dataframes for comparison, on basis of key columns :['symbol']

In [3]:
compare.diff[sorted(compare.diff, reverse=True)]

,volume_right,volume_left,volume_diff,text_right,text_left,text_diff,rows_present,quotedate_right,quotedate_left,quotedate_diff,...,high_right,high_left,high_diff,close_right,close_left,close_diff,adjustedclose_right,adjustedclose_left,adjustedclose_diff,_left_missing_columns
symbol,,,,,,,,,,,,,,,,,,,,,
AAN,1030097.0,1030099,2,a,a,NaN,both,2016-01-05,2016-01-05,NaN,...,23.30,23.30,NaN,23.120,20.000,-3.12,23.120,23.120,NaN,extra
AAP,1109219.0,1109219,NaN,a,b,DIFF.TRUE,both,2016-01-05,2016-01-05,NaN,...,153.79,153.79,NaN,151.200,151.200,NaN,151.200,151.200,NaN,extra
AAPL,55077191.0,55077191,NaN,a,a,NaN,both,2016-01-05,2016-03-04,5.0976e+06,...,105.85,105.85,NaN,102.714,102.714,NaN,102.714,102.714,NaN,extra
AAPO,55077191.0,55077191,NaN,1.5,1,-0.5,both,2016-01-05,2016-01-05,NaN,...,105.85,105.85,NaN,102.714,102.714,NaN,1.000,1.000,NaN,extra
AAPV,55077191.0,55077191,NaN,a,a,NaN,both,2016-01-05,2016-01-05,NaN,...,105.85,105.85,NaN,102.714,102.714,NaN,1.000,102.714,101.714,extra
AAPX,NaN,55077191,DIFF.TRUE,NaN,1,DIFF.TRUE,left_only,NaT,2016-02-05,DIFF.TRUE,...,NaN,105.85,DIFF.TRUE,NaN,102.714,DIFF.TRUE,NaN,1.000,DIFF.TRUE,extra

In [4]:
compare.metadata

,column_present,left_column,left_count,right_column,right_count,diff_column,diff_count
column,,,,,,,
text,both,text_left,11,text_right,10,text_diff,3
quotedate,both,quotedate_left,12,quotedate_right,11,quotedate_diff,2
high,both,high_left,12,high_right,11,high_diff,1
open,both,open_left,12,open_right,11,open_diff,1
close,both,close_left,12,close_right,11,close_diff,2
adjustedclose,both,adjustedclose_left,11,adjustedclose_right,10,adjustedclose_diff,2
volume,both,volume_left,12,volume_right,11,volume_diff,2
low,both,low_left,12,low_right,11,low_diff,1
extra,right_only,NaN,NaN,extra,9,NaN,NaN

In [5]:
compare.style_differ()

c:\users\aayush jain\appdata\local\programs\python\python37\lib\site-packages\pandas\core\indexing.py:1418: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)